# Generated by Django 3.2.16 on 2022-12-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0004_alter_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='Изображение'),
        ),
    ]
