# Generated by Django 3.2.16 on 2022-12-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0006_auto_20221227_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]