# Generated by Django 4.1.4 on 2022-12-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0009_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='my_order',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField()),
        ),
    ]