# Generated by Django 4.1.4 on 2022-12-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0011_alter_image_options_rename_places_image_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='my_order',
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
