# Generated by Django 4.1.4 on 2022-12-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0012_remove_image_my_order_alter_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='where_to_go.place', verbose_name='Место на карте'),
        ),
    ]
